language: node_js
node_js:
  - node # stable
  - '4' # LTS
branches:
  only:
    - master
env:
  global:
    - SAUCE_USERNAME=material-sauce
addons:
  sauce_connect: true
  jwt:
    secure: Iqwp6+hgpn8vhJAXxTbVgbScE8Q87qWCG+VhNvYFp38174QqLgmF80mjB501gCjrQ69BSePARVWN7VWAB0zt7H+QRs2Zqzyhkm0ctMtZhWFE5XmiOmyXtKpJQspmNMPeXVSrlY6BJRckK/cQ0aJDq9Ic/834AGXm9W2yHhnnxpHRRBuJHFeII4rDmO5fUKvikwtWFSnEXF0RuuhwH8DY0Wl/mGz9NiGqhq4QLIQOx/JzCs/06M+WEpMJH1hhowmgNztJDUI5cLUPot7b0YSzjtgVUF8oGjssh7pZ09NHZwMVUKG5PMxDEUDVrIrkYNQ0cDaFqDdRvXWdW64SSYVqikF9HSsha1XR9RObTfpHL3/SML8swXrkcnefBZHqNOoUnXsw/LRSCJ0kEOHovIb/rP9oU/L/OcqHeol4TDgDR41yQCYdEPnE7lX0L4GGl/GUVVdQ7cSPvi/V58kQrMIc1t1w5cGRwHexoI5kcLOMqJb48uHgtVdyXlulgXcQag8eu7E28p6eTKXiLs79a2GuL3+fhdpBqTF0+5b9ohp28jVE8PEdKMa5fc8+m/SUuKEuXHs4vbDAG+KFwSmWx/qBWks9Kp1Eh23nBscbLFbVrkFjQw6gLe/UspNv/WLbfAz74dLJe1SaoTV8fXD5LX7Yd0kwfCzaPVTvEHlvsUGQu2I=
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8bceea29a64b5fb7f608
    on_success: change
    on_failure: always
    on_start: never
